name: Anthony Wilkinson

title: Anthony Wilkinson
description: Notes and thoughts...
logo: images/MugshotJan2020Cropped.jpg


theme: jekyll-theme-minimal

url: https://ajwilkinson.github.io

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
